//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service_References.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем nickname из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        AuthorizeResponse Authorize(AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthorizeResponse> AuthorizeAsync(AuthorizeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем nickname из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        RegisterResponse Register(RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<RegisterResponse> RegisterAsync(RegisterRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetUserContactsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserContacts", ReplyAction="*")]
        GetUserContactsResponse GetUserContacts(GetUserContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<GetUserContactsResponse> GetUserContactsAsync(GetUserContactsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем contactNickname из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewContact", ReplyAction="*")]
        AddNewContactResponse AddNewContact(AddNewContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewContact", ReplyAction="*")]
        System.Threading.Tasks.Task<AddNewContactResponse> AddNewContactAsync(AddNewContactRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем DeleteContactResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteContact", ReplyAction="*")]
        DeleteContactResponse DeleteContact(DeleteContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteContact", ReplyAction="*")]
        System.Threading.Tasks.Task<DeleteContactResponse> DeleteContactAsync(DeleteContactRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetMessageHistoryResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageHistory", ReplyAction="*")]
        GetMessageHistoryResponse GetMessageHistory(GetMessageHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<GetMessageHistoryResponse> GetMessageHistoryAsync(GetMessageHistoryRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetUserByGuidResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByGuid", ReplyAction="*")]
        GetUserByGuidResponse GetUserByGuid(GetUserByGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<GetUserByGuidResponse> GetUserByGuidAsync(GetUserByGuidRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorize", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeRequestBody Body;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(AuthorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthorizeRequestBody() {
        }
        
        public AuthorizeRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeResponseBody Body;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(AuthorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthorizeResult;
        
        public AuthorizeResponseBody() {
        }
        
        public AuthorizeResponseBody(string AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string info;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string nickname, string password, string firstName, string lastName, string info) {
            this.nickname = nickname;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserContacts", Namespace="http://tempuri.org/", Order=0)]
        public GetUserContactsRequestBody Body;
        
        public GetUserContactsRequest() {
        }
        
        public GetUserContactsRequest(GetUserContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid guid;
        
        public GetUserContactsRequestBody() {
        }
        
        public GetUserContactsRequestBody(System.Guid guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserContactsResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetUserContactsResponseBody Body;
        
        public GetUserContactsResponse() {
        }
        
        public GetUserContactsResponse(GetUserContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserContactsResult;
        
        public GetUserContactsResponseBody() {
        }
        
        public GetUserContactsResponseBody(string GetUserContactsResult) {
            this.GetUserContactsResult = GetUserContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewContact", Namespace="http://tempuri.org/", Order=0)]
        public AddNewContactRequestBody Body;
        
        public AddNewContactRequest() {
        }
        
        public AddNewContactRequest(AddNewContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid userGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contactNickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        public AddNewContactRequestBody() {
        }
        
        public AddNewContactRequestBody(System.Guid userGuid, string contactNickname, string name) {
            this.userGuid = userGuid;
            this.contactNickname = contactNickname;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewContactResponse", Namespace="http://tempuri.org/", Order=0)]
        public AddNewContactResponseBody Body;
        
        public AddNewContactResponse() {
        }
        
        public AddNewContactResponse(AddNewContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewContactResult;
        
        public AddNewContactResponseBody() {
        }
        
        public AddNewContactResponseBody(string AddNewContactResult) {
            this.AddNewContactResult = AddNewContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContact", Namespace="http://tempuri.org/", Order=0)]
        public DeleteContactRequestBody Body;
        
        public DeleteContactRequest() {
        }
        
        public DeleteContactRequest(DeleteContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid userGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid contactGuid;
        
        public DeleteContactRequestBody() {
        }
        
        public DeleteContactRequestBody(System.Guid userGuid, System.Guid contactGuid) {
            this.userGuid = userGuid;
            this.contactGuid = contactGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContactResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeleteContactResponseBody Body;
        
        public DeleteContactResponse() {
        }
        
        public DeleteContactResponse(DeleteContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteContactResult;
        
        public DeleteContactResponseBody() {
        }
        
        public DeleteContactResponseBody(string DeleteContactResult) {
            this.DeleteContactResult = DeleteContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageHistory", Namespace="http://tempuri.org/", Order=0)]
        public GetMessageHistoryRequestBody Body;
        
        public GetMessageHistoryRequest() {
        }
        
        public GetMessageHistoryRequest(GetMessageHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid userGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid contactGuid;
        
        public GetMessageHistoryRequestBody() {
        }
        
        public GetMessageHistoryRequestBody(System.Guid userGuid, System.Guid contactGuid) {
            this.userGuid = userGuid;
            this.contactGuid = contactGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetMessageHistoryResponseBody Body;
        
        public GetMessageHistoryResponse() {
        }
        
        public GetMessageHistoryResponse(GetMessageHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageHistoryResult;
        
        public GetMessageHistoryResponseBody() {
        }
        
        public GetMessageHistoryResponseBody(string GetMessageHistoryResult) {
            this.GetMessageHistoryResult = GetMessageHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByGuid", Namespace="http://tempuri.org/", Order=0)]
        public GetUserByGuidRequestBody Body;
        
        public GetUserByGuidRequest() {
        }
        
        public GetUserByGuidRequest(GetUserByGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid guid;
        
        public GetUserByGuidRequestBody() {
        }
        
        public GetUserByGuidRequestBody(System.Guid guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByGuidResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetUserByGuidResponseBody Body;
        
        public GetUserByGuidResponse() {
        }
        
        public GetUserByGuidResponse(GetUserByGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserByGuidResult;
        
        public GetUserByGuidResponseBody() {
        }
        
        public GetUserByGuidResponseBody(string GetUserByGuidResult) {
            this.GetUserByGuidResult = GetUserByGuidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ServiceSoap>, ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthorizeResponse ServiceSoap.Authorize(AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public string Authorize(string nickname, string password) {
            AuthorizeRequest inValue = new AuthorizeRequest();
            inValue.Body = new AuthorizeRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            AuthorizeResponse retVal = ((ServiceSoap)(this)).Authorize(inValue);
            return retVal.Body.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizeResponse> ServiceSoap.AuthorizeAsync(AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizeResponse> AuthorizeAsync(string nickname, string password) {
            AuthorizeRequest inValue = new AuthorizeRequest();
            inValue.Body = new AuthorizeRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            return ((ServiceSoap)(this)).AuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegisterResponse ServiceSoap.Register(RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string nickname, string password, string firstName, string lastName, string info) {
            RegisterRequest inValue = new RegisterRequest();
            inValue.Body = new RegisterRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.info = info;
            RegisterResponse retVal = ((ServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RegisterResponse> ServiceSoap.RegisterAsync(RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<RegisterResponse> RegisterAsync(string nickname, string password, string firstName, string lastName, string info) {
            RegisterRequest inValue = new RegisterRequest();
            inValue.Body = new RegisterRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.info = info;
            return ((ServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetUserContactsResponse ServiceSoap.GetUserContacts(GetUserContactsRequest request) {
            return base.Channel.GetUserContacts(request);
        }
        
        public string GetUserContacts(System.Guid guid) {
            GetUserContactsRequest inValue = new GetUserContactsRequest();
            inValue.Body = new GetUserContactsRequestBody();
            inValue.Body.guid = guid;
            GetUserContactsResponse retVal = ((ServiceSoap)(this)).GetUserContacts(inValue);
            return retVal.Body.GetUserContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetUserContactsResponse> ServiceSoap.GetUserContactsAsync(GetUserContactsRequest request) {
            return base.Channel.GetUserContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetUserContactsResponse> GetUserContactsAsync(System.Guid guid) {
            GetUserContactsRequest inValue = new GetUserContactsRequest();
            inValue.Body = new GetUserContactsRequestBody();
            inValue.Body.guid = guid;
            return ((ServiceSoap)(this)).GetUserContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddNewContactResponse ServiceSoap.AddNewContact(AddNewContactRequest request) {
            return base.Channel.AddNewContact(request);
        }
        
        public string AddNewContact(System.Guid userGuid, string contactNickname, string name) {
            AddNewContactRequest inValue = new AddNewContactRequest();
            inValue.Body = new AddNewContactRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactNickname = contactNickname;
            inValue.Body.name = name;
            AddNewContactResponse retVal = ((ServiceSoap)(this)).AddNewContact(inValue);
            return retVal.Body.AddNewContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddNewContactResponse> ServiceSoap.AddNewContactAsync(AddNewContactRequest request) {
            return base.Channel.AddNewContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddNewContactResponse> AddNewContactAsync(System.Guid userGuid, string contactNickname, string name) {
            AddNewContactRequest inValue = new AddNewContactRequest();
            inValue.Body = new AddNewContactRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactNickname = contactNickname;
            inValue.Body.name = name;
            return ((ServiceSoap)(this)).AddNewContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeleteContactResponse ServiceSoap.DeleteContact(DeleteContactRequest request) {
            return base.Channel.DeleteContact(request);
        }
        
        public string DeleteContact(System.Guid userGuid, System.Guid contactGuid) {
            DeleteContactRequest inValue = new DeleteContactRequest();
            inValue.Body = new DeleteContactRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactGuid = contactGuid;
            DeleteContactResponse retVal = ((ServiceSoap)(this)).DeleteContact(inValue);
            return retVal.Body.DeleteContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeleteContactResponse> ServiceSoap.DeleteContactAsync(DeleteContactRequest request) {
            return base.Channel.DeleteContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeleteContactResponse> DeleteContactAsync(System.Guid userGuid, System.Guid contactGuid) {
            DeleteContactRequest inValue = new DeleteContactRequest();
            inValue.Body = new DeleteContactRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactGuid = contactGuid;
            return ((ServiceSoap)(this)).DeleteContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetMessageHistoryResponse ServiceSoap.GetMessageHistory(GetMessageHistoryRequest request) {
            return base.Channel.GetMessageHistory(request);
        }
        
        public string GetMessageHistory(System.Guid userGuid, System.Guid contactGuid) {
            GetMessageHistoryRequest inValue = new GetMessageHistoryRequest();
            inValue.Body = new GetMessageHistoryRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactGuid = contactGuid;
            GetMessageHistoryResponse retVal = ((ServiceSoap)(this)).GetMessageHistory(inValue);
            return retVal.Body.GetMessageHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetMessageHistoryResponse> ServiceSoap.GetMessageHistoryAsync(GetMessageHistoryRequest request) {
            return base.Channel.GetMessageHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetMessageHistoryResponse> GetMessageHistoryAsync(System.Guid userGuid, System.Guid contactGuid) {
            GetMessageHistoryRequest inValue = new GetMessageHistoryRequest();
            inValue.Body = new GetMessageHistoryRequestBody();
            inValue.Body.userGuid = userGuid;
            inValue.Body.contactGuid = contactGuid;
            return ((ServiceSoap)(this)).GetMessageHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetUserByGuidResponse ServiceSoap.GetUserByGuid(GetUserByGuidRequest request) {
            return base.Channel.GetUserByGuid(request);
        }
        
        public string GetUserByGuid(System.Guid guid) {
            GetUserByGuidRequest inValue = new GetUserByGuidRequest();
            inValue.Body = new GetUserByGuidRequestBody();
            inValue.Body.guid = guid;
            GetUserByGuidResponse retVal = ((ServiceSoap)(this)).GetUserByGuid(inValue);
            return retVal.Body.GetUserByGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetUserByGuidResponse> ServiceSoap.GetUserByGuidAsync(GetUserByGuidRequest request) {
            return base.Channel.GetUserByGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetUserByGuidResponse> GetUserByGuidAsync(System.Guid guid) {
            GetUserByGuidRequest inValue = new GetUserByGuidRequest();
            inValue.Body = new GetUserByGuidRequestBody();
            inValue.Body.guid = guid;
            return ((ServiceSoap)(this)).GetUserByGuidAsync(inValue);
        }
    }
}
