//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Contact = new HashSet<Contact>();
            this.Contact1 = new HashSet<Contact>();
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
        }
    
        public System.Guid ID { get; set; }
        public string Nickname { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
    }
}
